siteTitle = "effulgence // prayash thapa"
siteDescr = "Prayash Thapa (effulgence) is an audiovisual artist and programmer."
siteAuthor = "Prayash Thapa"

siteTelegramUrl = "#"
siteTwitterUrl = "twitter.com/iameffulgence"
siteGithubUrl = "github.com/prayasht"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = ""
