blogTitle = "effulgence // prayash thapa"
mastHead = "prayash thapa"
authorName = "Prayash Thapa"
shortName = "effulgence"
linkPrefix = ""
domain = "http://effulgence.io"
email = "prayash@effulgence.io"
description = "Effulgence is an audiovisual artist + programmer."
