blogTitle = "effulgence // prayash thapa"
mastHead = "prayash thapa"
authorName = "Prayash Thapa"
shortName = "effulgence"
linkPrefix = ""
domain = "http://effulgence.io"
email = "prayash@effulgence.io"
description = "Effulgence (Prayash Thapa) is an artist and software developer."
